steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["test"]

  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "asia-south1-docker.pkg.dev/ust-edgeops-dagility-dev/build/hellospring", "--build-arg=JAR_FILE=target/hello-spring-1.0.0.jar", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "asia-south1-docker.pkg.dev/ust-edgeops-dagility-dev/build/hellospring"]

  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
      gcloud deploy apply --file deploy/pipeline.yaml --region=asia-south1
      gcloud deploy apply --file deploy/dev.yaml --region=asia-south1
      gcloud deploy apply --file deploy/prod.yaml --region=asia-south1
      gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=asia-south1 --skaffold-file=skaffold.yaml --impersonate-service-account=sftp-tf-iac-sa@ust-edgeops-dagility-dev.iam.gserviceaccount.com

#images: ["asia-south1-docker.pkg.dev/ust-edgeops-dagility-dev/build/hellospring"]

options:
  logging: CLOUD_LOGGING_ONLY
  #serviceAccount: sftp-tf-iac-sa@ust-edgeops-dagility-dev.iam.gserviceaccount.com
